#!/usr/bin/env python3
"""Turn a third-party Odoo module zip into a ConfigMap manifest mounted as its addon directory.

Usage: odoo-module-configmap.py <module.zip> <configmap name> > platform/<file>.yaml

Tests and App Store images (static/description, except icon.png) are left out: Odoo doesn't need them at runtime,
and a ConfigMap holds at most 1 MiB. Text files go to data, binary files to binaryData; `items` in the volume maps
the flat keys back to the module's paths (see the volume in odoo.yaml).
"""
import base64, hashlib, io, sys, zipfile

path, name = sys.argv[1], sys.argv[2]
raw = open(path, "rb").read()
archive = zipfile.ZipFile(io.BytesIO(raw))
module = archive.namelist()[0].split("/")[0]
text, binary, items = {}, {}, []
for entry in sorted(archive.namelist()):
    rel = entry[len(module) + 1:]
    if not rel or entry.endswith("/") or rel.startswith("tests/"):
        continue
    if rel.startswith("static/description/") and rel != "static/description/icon.png":
        continue
    key = rel.replace("/", "__")
    content = archive.read(entry)
    try:
        text[key] = content.decode("utf-8")
    except UnicodeDecodeError:
        binary[key] = base64.b64encode(content).decode()
    items.append((key, rel))

out = [
    f"# Third-party Odoo module {module}, generated by tools/odoo-module-configmap.py from",
    f"# {path.split('/')[-1]} (sha256 {hashlib.sha256(raw).hexdigest()}). Don't edit by hand: regenerate.",
    f"# Volume items for odoo.yaml (key -> path): {len(items)} files.",
    "apiVersion: v1",
    "kind: ConfigMap",
    "metadata:",
    f"  name: {name}",
    "  namespace: odoo",
    "  annotations:",
    '    argocd.argoproj.io/sync-wave: "90"',
    "data:",
]
for key, value in text.items():
    lines = value.split("\n")
    if lines and lines[-1] == "":
        lines = lines[:-1]
        out.append(f"  {key}: |")
    else:
        out.append(f"  {key}: |-")
    out.extend(("    " + l if l else "") for l in lines)
if binary:
    out.append("binaryData:")
    out.extend(f"  {key}: {value}" for key, value in binary.items())
print("\n".join(out))
print("# items:", file=sys.stderr)
for key, rel in items:
    print(f"            - key: {key}\n              path: {rel}", file=sys.stderr)
