apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-foundation
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: oci://ghcr.io/bakedchicken/homelab-platform
    targetRevision: latest
    path: foundation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: -1
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-data
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: oci://ghcr.io/bakedchicken/homelab-platform
    targetRevision: latest
    path: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: -1
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-identity
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: oci://ghcr.io/bakedchicken/homelab-platform
    targetRevision: latest
    path: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: -1
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: oci://ghcr.io/bakedchicken/homelab-platform
    targetRevision: latest
    path: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: -1
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: oci://ghcr.io/bakedchicken/homelab-platform
    targetRevision: latest
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: -1
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
