apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: reloader
      targetRevision: 2.2.17
      helm:
        valuesObject:
          reloader:
            enableHA: true
            reloadStrategy: annotations
            deployment:
              replicas: 2
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      podAffinityTerm:
                        labelSelector:
                          matchLabels:
                            app: reloader-reloader
                        topologyKey: kubernetes.io/hostname
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  memory: 256Mi
              pod:
                annotations:
                  prometheus.io/scrape: "true"
                  prometheus.io/port: "9090"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
